name: Staging Deploy Docker Image for Lambdas
description: "Build docker image, tag, upload and set on lambdas"
inputs:
  lambda_names:
    description: Function names separated by comma
    required: false
  prefix_function_names:
    description: Function prefix to match
    required: true
  prefix_function_names:
    description: Function prefix to match
    required: true
  aws_access_key_id:
    description: AWS Key ID
    required: true
  aws_secret_access_key:
    description: AWS Secret Access Key
    required: true
  ecr_image_name:
    description: Define the repository of ECR image
    required: true
  ecr_image_tag:
    description: Define the tag of ECR image
    required: true
  build_working_directory:
    description: Define the path of working directory of code to build Docker image
    required: true
  docker_build_extra_args:
    description: Define the extra arguments that you will set to docker build command
    required: false
    default: ""
  with_testing_db:
    description: Wether is necessary a testing db or not
    required: false
    default: "false"
  db_schemas:
    description: DB schemas list to create separated by a space
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up test db
      id: set-up-test-db
      if: ${{ inputs.with_testing_db == 'true' }}
      uses: meetlara/set-up-test-db@main
      with:
        db_schemas: ${{ inputs.db_schemas }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup Sam
      uses: aws-actions/setup-sam@v2
    - name: Build, tag, and push image to Amazon ECR and update function
      shell: bash
      working-directory: ${{ inputs.build_working_directory }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_image_name }}
        FUNCTION_NAMES: ${{ inputs.lambda_names }}
        PREFIX_FUNCTION_NAMES: ${{ inputs.prefix_function_names }}
        ECR_IMAGE_NAME: ${{ inputs.ecr_image_tag }}
      run: |
        if docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_NAME ; then
            echo "Already existed image; skipping."
        else
          docker build ${{ inputs.docker_build_extra_args }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_NAME -f ./Dockerfile.serverless .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_NAME
        fi

        FUNCTION_LIST=$(aws lambda list-functions --query "Functions[?starts_with(FunctionName, '${PREFIX_FUNCTION_NAMES}')].FunctionName | @.join(' ', @)" --output text)
        if [ -z "${FUNCTION_NAMES}" ]; then
          FUNCTION_LIST="$FUNCTION_LIST $AWS_FUNCTIONS"
        fi

        for functionName in $FUNCTION_LIST; do
          aws lambda update-function-code --function-name $functionName --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_NAME
        done
        
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_NAME"
